[package]
name = "spaaaace-shared"
version = "0.1.0"
authors = []
workspace = "../"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[features]

[dependencies]
bevy_ecs = { version = "0.9", default-features=false}
naia-shared = { version = "0.14.0"}
cfg-if = { version = "1.0" }
log = { version = "0.4" }